services:
    rxu.PostsMerging.listener:
        class: rxu\PostsMerging\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @notification_manager
            - @dispatcher
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
